name: Update gist with Nintendo Switch Game stats
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update gist
        uses: Swilder-M/nintendo-switch-box@master
        env:
          NINTENDO_SESSION_TOKEN: ${{ secrets.NINTENDO_SESSION_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
